eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
server:
  port: 6867
spring:
  application:
    name: SAVE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pawen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: w15038145966
  redis:
    host: 139.196.157.116
    port: 6379
  rabbitmq:
    host: 139.196.157.116
    port: 5672
    username: guest
    password: guest
    virtual-host: /