
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
server:
  port: 6869
spring:
  application:
    name: CUTWORD
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pawen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: w15038145966
